<?php /* Generated By SBP *//*:C:\wamp\www\sbp\tests\sbp\files\.src\assignation.php:*/ 
$texte = substr($texte, 0, 2);
$texte = substr($texte, 0, 2);

$_POST['username'] = stripslashes($_POST['username']);
$_POST['username'] = stripslashes($_POST['username']);
