<?php /* Generated By SBP */ 
$texte = substr($texte, 0, 2);
$texte = substr($texte, 0, 2);

$_POST['username'] = stripslashes($_POST['username']);
$_POST['username'] = stripslashes($_POST['username']);
?>