<?php /* Generated By SBP */ 

class Bidule {
	public function truc(){
		echo "truc";
	} public function machin(){
		echo "machin";
	} public function chose(){
		echo "chose";
}}
(new \Sbp\Chainer(new Bidule))
	->truc()
	->machin()
	->chose();
