<?php /* Generated By SBP *//*:C:\wamp\www\sbp\tests\sbp\files\.src\chainer.php:*/ 

class Bidule {
	public function truc(){
		echo "truc";
	} public function machin(){
		echo "machin";
	} public function chose(){
		echo "chose";
}}
(new \Sbp\Chainer(new Bidule))
	->truc()
	->machin()
	->chose();
