<?php /* Generated By SBP *//*:C:\wamp\www\sbp/tests/sbp/files/.src/classe_methodes.php:*/  
class Foo {
	public function pub () {
		echo "Méthode publique"; 
	} protected function pro ($arguments) {
		echo "Méthode protégée"; 
	} private function pri ($a, $b) {
		return "Méthode privée"; 
	} public static function sta () {
		return "Méthode statique et publique"; 
}}?>