<?php /* Generated By SBP */ 
class Foo {
	public function pub () {
		echo "Méthode publique";
	} protected function pro ($arguments) {
		echo "Méthode protégée";
	} private function pri ($a, $b) {
		return "Méthode privée";
	} static public function sta () {
		return "Méthode statique et publique";
}}?>