<?php /* Generated By SBP *//*:C:\wamp\www\sbp/tests/sbp/files/.src/classe_constante.php:*/  
class Bar {
	const NAME = "Foo Bar"; 
 
	public static function getName () {
		return  static::NAME; 
 
	} public static function printName () {
		echo static::NAME; 
}}?>