<?php /* Generated By SBP */ 
class Foo {
	public function getAttrbiute () {
		return $this->attribute;
    }
	protected function doubleAttrbiute () {
		$this->attribute *=2;
    }
	protected function doubleTwiceAttrbiute () {
		$this->doubleAttrbiute();
		$this->doubleAttrbiute();
}}?>