<?php /* Generated By SBP */
class ClasseMere {
	// Contenu de la classe mère
}
class ClasseFille extends ClasseMere {
	// Contenu de la classe fille
}
class ClasseFille extends ClasseMere implements Interface1, Interface2 {
	// Contenu de la classe fille
}?>