<?php /* Generated By SBP */ 

if(! function_exists('__sbp_in')) { function __sbp_in ($needle, $haystack = null) {
	if (func_num_args() === 1) {
		return  array_search(true, $neelde);
	} return  is_array($haystack) ?
		in_array($needle, $haystack) :
		strpos($haystack, $needle) !== false;
}}
if (__sbp_in(5, [3, 5, 7, 11])) {
	echo "5 is in [3, 5, 7, 11]";
} else {
	echo "5 isn't in [3, 5, 7, 11]";
}
if (__sbp_in("BA", "tagaBAduru")) {
	echo "BA is in tagaBAduru";
} else {
	echo "BA isn't in tagaBAduru";
}
if (__sbp_in([false, true, true, false])) {
	echo "There is true values";
} else {
	echo "There is no true value";
}