<?php /* Generated By SBP */  
function cube ($i) {
	return $i*$i*$i; 
 
}$cubes = array_map( 
	function ($i) {
		return $i*$i*$i; 
 
	} ,[1, 2, 3] 
); 
 
if (! function_exists('cube')) { function cube ($i) {
	return pow($i, 3); 
} }?>