<?php /* Generated By SBP */ 

$a = false;

if ($a) {}
else{
    echo "Hello";
}
try{
    echo " world";
}catch (Exception $e) {}

echo "!";

function yoh () {
    if ($a) {}
    else{
        echo "Hello";
    }
    try{
        echo " world";
    } catch (Exception $e) {}

    echo "!";
}
