<?php /* Generated By SBP */   class MaClasse extends Object {  	
	private $privateAttribute = 42;
	protected $protectedAttribute = "foo";
	public $publicAttribute = "bar";
	
	private function privateMethod () {
		return $this->privateAttribute;
    }
	protected function protectedMethod ($val) {
		$this->privateAttribute = $val;
    }
	public function publicMethod () {
		echo $this->privateAttribute;
		return  true;
    }
	public function __destruct () {

		log("/sbp/files/ma_classe.class.php");
		// ma_classe.class.php
		// ma_classe
		// maClasse
}}
?>