<?php /* Generated By SBP *//*:C:\wamp\www\sbp\tests\sbp\files\.src\return.php:*/  
 
if (! function_exists('sevenTimes')) { function sevenTimes($num) {
    return  7 * $num; 
 
} }$answear = sevenTimes(6); 
 
return  $answear; 
