<?php /* Generated By SBP */  
 
echo $_SERVER['QUERY_STRING']; 
echo $_SERVER['AUTH_USER']; 
echo $_SERVER['AUTH_PW']; 
echo $_SERVER['PATH_INFO']; 
echo $_SERVER['REQUEST_METHOD']; 
echo $_SERVER['HTTP_USER_AGENT']; 
echo $_SERVER['HTTP_REFERER']; 
echo $_SERVER['HTTP_HOST']; 
echo $_SERVER['REQUEST_URI']; 
echo $_SERVER['REMOTE_ADDR'];