<?php /* Generated By SBP */ 

echo (new \Sbp\Handler(5))->sqrt() . "\n";
echo (new \Sbp\Handler(5))->pow(4) . "\n";

$array = array(
	'toto' => 4,
	'tata' => 5,
	'lulu' => 6
);
echo (new \Sbp\Handler((new \Sbp\Handler($array))->keys()))->implode(', ') . "\n";

echo (new \Sbp\Handler((new \Sbp\Handler(array(
	'toto' => 4,
	'tata' => 5,
	'lulu' => 6
)))->keys()))->implode(', ') . "\n";