<?php /* Generated By SBP */  
 
switch($medal) {
	case "gold": 
		echo "Médaille d'or"; 
		break; 
	case "silver": 
		echo "Médaille d'argent"; 
		break; 
	default: 
		echo "Médaille de bronze"; 
 
}?>