#!/usr/bin/php
<?php
// Hook configuration
$project = 'My Test';
 
// Tell the commiter what the hook is doing
echo PHP_EOL;
echo '+ Starting unit tests'.PHP_EOL;
 
// Execute project unit tests
exec('phpunit ' . realpath(__DIR__ . '/..'), $output, $returnCode);
 
// if the build failed, output a summary and fail
if ($returnCode !== 0)
{
    // find the line with the summary; this might not be the last
    while (($minimalTestSummary = array_pop($output)) !== null)
    {
        if (strpos($minimalTestSummary, 'Tests:') !== false)
        {
            break;
        }
    }
 
    // output the status and abort the commit
    echo '+ Test suite for '.$project.' failed:'.PHP_EOL;
    echo $minimalTestSummary;
    echo chr(27).'[0m'.PHP_EOL; // disable colors and add a line break
    echo PHP_EOL;
    exit(1);
}
 
echo '+ All tests for '.$project.' passed.'.PHP_EOL;
echo PHP_EOL;
exit(0);